// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2025, 12:37:19 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/miadugas/Desktop/grave_goods/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miadugas/Desktop/grave_goods/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miadugas/Desktop/grave_goods/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miadugas/Desktop/grave_goods/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miadugas/Desktop/grave_goods/plugins/**/*.{js,ts,mjs}","/Users/miadugas/Desktop/grave_goods/composables/**/*.{js,ts,mjs}","/Users/miadugas/Desktop/grave_goods/utils/**/*.{js,ts,mjs}","/Users/miadugas/Desktop/grave_goods/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/miadugas/Desktop/grave_goods/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/miadugas/Desktop/grave_goods/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;